# Generated by Django 4.2.15 on 2024-08-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=2180, null=True)),
                ('source_code', models.CharField(blank=True, max_length=2180, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
